DROP DATABASE Student;

CREATE DATABASE College;
USE College;
DROP DATABASE College;
CREATE DATABASE College;
USE College;
CREATE TABLE Student(
age INT UNIQUE);
INSERT INTO Student
(age)
VALUES
(123),
(34),
(872);